{{- if and .Values.tenx.enabled .Values.tenx.licenseJwt }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-tenx-license
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
type: Opaque
data:
  license-jwt: {{ .Values.tenx.licenseJwt | b64enc | quote }}
{{- end }}
{{- if and .Values.tenx.enabled .Values.tenx.gitToken }}
{{- if .Values.tenx.licenseJwt }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-tenx-git-token
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.tenx.gitToken | b64enc | quote }}
{{- end }}
